syntax = "proto3";

package cron_v1;

import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/empty.proto";

option go_package = "github.com/Georgi-Progger/cron/pkg/cron_v1;cron_v1";

service CronV1 {
    rpc Start(StartJobRequest) returns (StartJobResponse);
    rpc Stop(StopJobRequest) returns (StopJobResponse);
    rpc ListJobs(ListJobsRequest) returns (ListJobsResponse);
}

message ListJobsRequest {}

message ListJobsResponse {
    repeated JobInfo jobs = 1;
}

message JobInfo {
    string name = 1;
    JobStatus status = 2;
    google.protobuf.Timestamp last_run = 3;
    google.protobuf.Timestamp next_run = 4;
}

message StartJobRequest {
    string name = 1;
    google.protobuf.Duration interval = 2;
    google.protobuf.Timestamp start_from = 3;
}

message StartJobResponse {
    string name = 1;
    bool started = 2;
    string error_message = 3;
}

message StopJobRequest {
    string name = 1;
}

message StopJobResponse {
    string name = 1;
    bool stopped = 2;
    int32 processed_count = 3;
    google.protobuf.Timestamp last_processed_time = 4;
}

enum JobStatus {
    JOB_STATUS_UNKNOWN = 0;
    JOB_STATUS_PENDING = 1;
    JOB_STATUS_RUNNING = 2;
    JOB_STATUS_STOPPED = 3;
    JOB_STATUS_ERROR = 4;
}