syntax = "proto3";

package cron_v1;

import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/empty.proto";

option go_package = "github.com/Georgi-Progger/cronlib/pb/cron_v1;cron_v1";

service CronV1 {
    rpc Start(StartJobRequest) returns (StartJobResponse);
    rpc Stop(StopJobRequest) returns (StopJobResponse);
    rpc GetJob(GetJobRequest) returns (GetJobResponse);
    rpc ListJobs(google.protobuf.Empty) returns (ListJobsResponse);
}

message StartJobRequest {
    string name = 1;
    google.protobuf.Timestamp until = 2;    
}

message StartJobResponse {
    string name = 1;
    Status status = 2;
    string error_message = 3;
}

message StopJobRequest {
    string name = 1;
}

message StopJobResponse {
    Status status = 1;
    string error_message = 2;
}

message GetJobRequest {
    string name = 1;
}

message GetJobResponse {
    JobInfo job = 1;
}

message ListJobsResponse {
    repeated JobInfo jobs = 1;
}

message JobInfo {
    string name = 1;
    Status status = 2;
    google.protobuf.Timestamp last_run = 3;
    string error = 4;
}

enum Status {
    RUNNING = 0;
    STOPPED = 1;
    ERROR = 2;
}