// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.3
// source: cron.proto

package cron_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_RUNNING Status = 0
	Status_STOPPED Status = 1
	Status_ERROR   Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "RUNNING",
		1: "STOPPED",
		2: "ERROR",
	}
	Status_value = map[string]int32{
		"RUNNING": 0,
		"STOPPED": 1,
		"ERROR":   2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_cron_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_cron_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{0}
}

type StartJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobRequest) Reset() {
	*x = StartJobRequest{}
	mi := &file_cron_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobRequest) ProtoMessage() {}

func (x *StartJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobRequest.ProtoReflect.Descriptor instead.
func (*StartJobRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{0}
}

func (x *StartJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartJobRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

type StartJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=cron_v1.Status" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartJobResponse) Reset() {
	*x = StartJobResponse{}
	mi := &file_cron_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartJobResponse) ProtoMessage() {}

func (x *StartJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartJobResponse.ProtoReflect.Descriptor instead.
func (*StartJobResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{1}
}

func (x *StartJobResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StartJobResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_RUNNING
}

func (x *StartJobResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StopJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobRequest) Reset() {
	*x = StopJobRequest{}
	mi := &file_cron_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobRequest) ProtoMessage() {}

func (x *StopJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobRequest.ProtoReflect.Descriptor instead.
func (*StopJobRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{2}
}

func (x *StopJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type StopJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        Status                 `protobuf:"varint,1,opt,name=status,proto3,enum=cron_v1.Status" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopJobResponse) Reset() {
	*x = StopJobResponse{}
	mi := &file_cron_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopJobResponse) ProtoMessage() {}

func (x *StopJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopJobResponse.ProtoReflect.Descriptor instead.
func (*StopJobResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{3}
}

func (x *StopJobResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_RUNNING
}

func (x *StopJobResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_cron_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Job           *JobInfo               `protobuf:"bytes,1,opt,name=job,proto3" json:"job,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobResponse) Reset() {
	*x = GetJobResponse{}
	mi := &file_cron_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobResponse) ProtoMessage() {}

func (x *GetJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobResponse.ProtoReflect.Descriptor instead.
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{5}
}

func (x *GetJobResponse) GetJob() *JobInfo {
	if x != nil {
		return x.Job
	}
	return nil
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobInfo             `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_cron_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{6}
}

func (x *ListJobsResponse) GetJobs() []*JobInfo {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type JobInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=cron_v1.Status" json:"status,omitempty"`
	LastRun       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobInfo) Reset() {
	*x = JobInfo{}
	mi := &file_cron_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobInfo) ProtoMessage() {}

func (x *JobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cron_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobInfo.ProtoReflect.Descriptor instead.
func (*JobInfo) Descriptor() ([]byte, []int) {
	return file_cron_proto_rawDescGZIP(), []int{7}
}

func (x *JobInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobInfo) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_RUNNING
}

func (x *JobInfo) GetLastRun() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRun
	}
	return nil
}

func (x *JobInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_cron_proto protoreflect.FileDescriptor

const file_cron_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"cron.proto\x12\acron_v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\"W\n" +
	"\x0fStartJobRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x05until\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\"t\n" +
	"\x10StartJobResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0f.cron_v1.StatusR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"$\n" +
	"\x0eStopJobRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"_\n" +
	"\x0fStopJobResponse\x12'\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0f.cron_v1.StatusR\x06status\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"#\n" +
	"\rGetJobRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"4\n" +
	"\x0eGetJobResponse\x12\"\n" +
	"\x03job\x18\x01 \x01(\v2\x10.cron_v1.JobInfoR\x03job\"8\n" +
	"\x10ListJobsResponse\x12$\n" +
	"\x04jobs\x18\x01 \x03(\v2\x10.cron_v1.JobInfoR\x04jobs\"\x93\x01\n" +
	"\aJobInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0f.cron_v1.StatusR\x06status\x125\n" +
	"\blast_run\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\alastRun\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error*-\n" +
	"\x06Status\x12\v\n" +
	"\aRUNNING\x10\x00\x12\v\n" +
	"\aSTOPPED\x10\x01\x12\t\n" +
	"\x05ERROR\x10\x022\xfb\x01\n" +
	"\x06CronV1\x12<\n" +
	"\x05Start\x12\x18.cron_v1.StartJobRequest\x1a\x19.cron_v1.StartJobResponse\x129\n" +
	"\x04Stop\x12\x17.cron_v1.StopJobRequest\x1a\x18.cron_v1.StopJobResponse\x129\n" +
	"\x06GetJob\x12\x16.cron_v1.GetJobRequest\x1a\x17.cron_v1.GetJobResponse\x12=\n" +
	"\bListJobs\x12\x16.google.protobuf.Empty\x1a\x19.cron_v1.ListJobsResponseB6Z4github.com/Georgi-Progger/cronlib/pb/cron_v1;cron_v1b\x06proto3"

var (
	file_cron_proto_rawDescOnce sync.Once
	file_cron_proto_rawDescData []byte
)

func file_cron_proto_rawDescGZIP() []byte {
	file_cron_proto_rawDescOnce.Do(func() {
		file_cron_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cron_proto_rawDesc), len(file_cron_proto_rawDesc)))
	})
	return file_cron_proto_rawDescData
}

var file_cron_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cron_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cron_proto_goTypes = []any{
	(Status)(0),                   // 0: cron_v1.Status
	(*StartJobRequest)(nil),       // 1: cron_v1.StartJobRequest
	(*StartJobResponse)(nil),      // 2: cron_v1.StartJobResponse
	(*StopJobRequest)(nil),        // 3: cron_v1.StopJobRequest
	(*StopJobResponse)(nil),       // 4: cron_v1.StopJobResponse
	(*GetJobRequest)(nil),         // 5: cron_v1.GetJobRequest
	(*GetJobResponse)(nil),        // 6: cron_v1.GetJobResponse
	(*ListJobsResponse)(nil),      // 7: cron_v1.ListJobsResponse
	(*JobInfo)(nil),               // 8: cron_v1.JobInfo
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_cron_proto_depIdxs = []int32{
	9,  // 0: cron_v1.StartJobRequest.until:type_name -> google.protobuf.Timestamp
	0,  // 1: cron_v1.StartJobResponse.status:type_name -> cron_v1.Status
	0,  // 2: cron_v1.StopJobResponse.status:type_name -> cron_v1.Status
	8,  // 3: cron_v1.GetJobResponse.job:type_name -> cron_v1.JobInfo
	8,  // 4: cron_v1.ListJobsResponse.jobs:type_name -> cron_v1.JobInfo
	0,  // 5: cron_v1.JobInfo.status:type_name -> cron_v1.Status
	9,  // 6: cron_v1.JobInfo.last_run:type_name -> google.protobuf.Timestamp
	1,  // 7: cron_v1.CronV1.Start:input_type -> cron_v1.StartJobRequest
	3,  // 8: cron_v1.CronV1.Stop:input_type -> cron_v1.StopJobRequest
	5,  // 9: cron_v1.CronV1.GetJob:input_type -> cron_v1.GetJobRequest
	10, // 10: cron_v1.CronV1.ListJobs:input_type -> google.protobuf.Empty
	2,  // 11: cron_v1.CronV1.Start:output_type -> cron_v1.StartJobResponse
	4,  // 12: cron_v1.CronV1.Stop:output_type -> cron_v1.StopJobResponse
	6,  // 13: cron_v1.CronV1.GetJob:output_type -> cron_v1.GetJobResponse
	7,  // 14: cron_v1.CronV1.ListJobs:output_type -> cron_v1.ListJobsResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_cron_proto_init() }
func file_cron_proto_init() {
	if File_cron_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cron_proto_rawDesc), len(file_cron_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cron_proto_goTypes,
		DependencyIndexes: file_cron_proto_depIdxs,
		EnumInfos:         file_cron_proto_enumTypes,
		MessageInfos:      file_cron_proto_msgTypes,
	}.Build()
	File_cron_proto = out.File
	file_cron_proto_goTypes = nil
	file_cron_proto_depIdxs = nil
}
